//const API_BASE_URL_DEVELOPMENT: string  = 'https://testazure1234.azurewebsites.net';
const API_BASE_URL_DEVELOPMENT: string  = 'https://localhost:44309';
const API_BASE_URL_PRODUCTION :string = 'https://aspnetcorereacttutorial-aspnetserver.azurewebsites.net';


const ENDPOINTS = {
    GET_ALL_POSTS: 'Users',
    GET_ALL_LINKS: 'Url/GetAll',
    GET_POST_BY_ID: 'Users',
    CREATE_POST: 'Users',
    UPDATE_POST: 'Users',
    DELETE_POST_BY_ID: 'Users',
    LOGIN_POST: 'Users/authenticate',
    REGISTER_POST: 'Users/Create',
    CREATE_SHORTER_LINK: 'Url/Create',
    GET_LINK_BY_ID: 'Url/getById',
    GET_USER_BY_ID: 'Users/getById',
    DELETE_ULR_BY_ID: 'Url/Delete'
    
   

};

const development = {
    BASE_URL: `${API_BASE_URL_DEVELOPMENT}`,
    API_URL_GET_ALL_POSTS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_POSTS}`,
    API_URL_GET_POST_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_POST_BY_ID}`,
    API_URL_CREATE_POST: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_POST}`,
    API_URL_UPDATE_POST: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_POST}`,
    API_URL_DELETE_POST_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_POST_BY_ID}`,
    API_URL_LOGIN_POST: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.LOGIN_POST}`,
    API_URL_CREATE_LINK_POST: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_SHORTER_LINK}`,
    API_URL_REGISTER_POST: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.REGISTER_POST}`,
 
    API_URL_GET_ALL_LINKS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_LINKS}`,
    API_URL_GET_LINK_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_LINK_BY_ID}`,
    API_URL_GET_USER_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_USER_BY_ID}`,

    API_URL_DELETE_URL_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_ULR_BY_ID}`
      

};

const production = {
    BASE_URL: `${API_BASE_URL_DEVELOPMENT}`,
    API_URL_GET_ALL_POSTS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_POSTS}`,
    API_URL_GET_POST_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_POST_BY_ID}`,
    API_URL_CREATE_POST: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_POST}`,
    API_URL_UPDATE_POST: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_POST}`,
    API_URL_DELETE_POST_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_POST_BY_ID}`,
    API_URL_CREATE_LINK_POST: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_SHORTER_LINK}`,
    API_URL_LOGIN_POST: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.LOGIN_POST}`,
    API_URL_REGISTER_POST: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.REGISTER_POST}`,

    API_URL_GET_ALL_LINKS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_LINKS}`,
    API_URL_GET_LINK_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_LINK_BY_ID}`,
    API_URL_GET_USER_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_USER_BY_ID}`,

    API_URL_DELETE_URL_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_ULR_BY_ID}`
};
const Constants = process.env.NODE_ENV === 'development' ? development : production;

export default Constants;
